version: '3.5'
services:
  postgresql:
    platform: linux/amd64
    container_name: kb-postgresql
    restart: always
    build:
      context: ./.docker/postgresql
      dockerfile: Dockerfile
    environment: 
      POSTGRES_DB: users
      POSTGRES_USER: kb-admin
      POSTGRES_PASSWORD: 4lp<!r0o2
    ports:
      - "5472:5432"
    volumes:
    - './.docker/postgres_data:/var/lib/postgresql/data'
    - ./.docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql